=== clemenswitt/pp/XML/5-3-2/telefonbuch.dtd
<!ELEMENT telefonbuch (verweis*)>
<!ELEMENT verweis (vorname, name, strasse, postleitzahl, ort)>

<!ELEMENT vorname (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT strasse (#PCDATA)>
<!ELEMENT postleitzahl (#PCDATA)>
<!ELEMENT ort (#PCDATA)>

=== clemenswitt/pp/XML/5-3-2/telefonbuch.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<?xml-stylesheet type="text/xsl" href="telefonbuch.xsl"?>
<!DOCTYPE telefonbuch SYSTEM "telefonbuch.dtd">

<telefonbuch>
	<verweis>
		<vorname>Max und Moritz</vorname>
		<name>Mustermann</name>
		<strasse>Hauptstr. 23</strasse>
		<postleitzahl>30102</postleitzahl>
		<ort>Hannover</ort>
	</verweis>
	<verweis>
		<vorname>Max</vorname>
		<name>Mustermann</name>
		<strasse>Hauptstr. 2</strasse>
		<postleitzahl>30102</postleitzahl>
		<ort>Hannover</ort>
	</verweis>
	<verweis>
		<vorname>Peter</vorname>
		<name>Peters</name>
		<strasse>Sackgasse 1</strasse>
		<postleitzahl>50823</postleitzahl>
		<ort>Köln</ort>
	</verweis>
	<verweis>
		<vorname>Max</vorname>
		<name>Mustermann</name>
		<strasse>Hauptstr. 2</strasse>
		<postleitzahl>30102</postleitzahl>
		<ort>Hannover</ort>
	</verweis>
	<verweis>
		<vorname>Peter</vorname>
		<name>Peters</name>
		<strasse>Sackgasse 1</strasse>
		<postleitzahl>50823</postleitzahl>
		<ort>Köln</ort>
	</verweis>
	<verweis>
		<vorname>Max</vorname>
		<name>Mustermann</name>
		<strasse>Hauptstr. 2</strasse>
		<postleitzahl>30102</postleitzahl>
		<ort>Hannover</ort>
	</verweis>
	<verweis>
		<vorname>Peter</vorname>
		<name>Peters</name>
		<strasse>Sackgasse 1</strasse>
		<postleitzahl>50823</postleitzahl>
		<ort>Köln</ort>
	</verweis>
	<verweis>
		<vorname>Max</vorname>
		<name>Mustermann</name>
		<strasse>Hauptstr. 2</strasse>
		<postleitzahl>30102</postleitzahl>
		<ort>Hannover</ort>
	</verweis>
	<verweis>
		<vorname>Peter</vorname>
		<name>Peters</name>
		<strasse>Sackgasse 1</strasse>
		<postleitzahl>50823</postleitzahl>
		<ort>Köln</ort>
	</verweis>
	<verweis>
		<vorname>Max</vorname>
		<name>Mustermann</name>
		<strasse>Hauptstr. 2</strasse>
		<postleitzahl>30102</postleitzahl>
		<ort>Hannover</ort>
	</verweis>
	<verweis>
		<vorname>Peter</vorname>
		<name>Peters</name>
		<strasse>Sackgasse 1</strasse>
		<postleitzahl>50823</postleitzahl>
		<ort>Köln</ort>
	</verweis>
</telefonbuch>
